### ISSUE TITLE
Problemas ao informar a URL

### ISSUE THREAD

**Issue by pachecobruno** [fontanfellipe/media-cart#1]
O sistema não está se comportando como deveria.
Ao fornecer uma URL de image o console apresenta um erro e o sistema não executa a verificação.

URL utilizada durante o teste:
* https://github.com/fontanfellipe/media-cart/raw/master/prototipo.png

Veja abaixo o erro apresentado:

![image](https://user-images.githubusercontent.com/592040/77977176-58b3cb80-72d5-11ea-8396-7c5666eb6330.png)

**Comment by fontanfellipe** [comment]
Acredito que o erro foi resolvido.
Testei com outras várias URLs além dessa de exemplo.
![urlISSUE](https://user-images.githubusercontent.com/55624137/78031930-9860ce80-733a-11ea-8807-eae2719497c7.PNG)
