### ISSUE TITLE
Separação de código

### ISSUE THREAD

**Issue by pachecobruno** [fontanfellipe/media-cart#2]
Um uma aplicação saudável, precisamos separar algumas camadas e dessa formar manter o código mais fácil de evoluir e crescer. Na sua solução, parece que a camada regras de negócio e serviços estão amarradas ao comportamento da tela. Sugiro realizar a separação dessas responsabilidades.

Algum locais onde isso acontece:

https://github.com/fontanfellipe/media-cart/blob/f6585cc5eb2bc7fcf3a1e6987790fd656bcbee7d/src/components/GridCart.js#L32

https://github.com/fontanfellipe/media-cart/blob/f6585cc5eb2bc7fcf3a1e6987790fd656bcbee7d/src/components/MediaSelection.js#L125

Consegue ajustar? @fontanfellipe

**Comment by fontanfellipe** [comment]
Super válida essa questão Bruno. Acabei de fazer um commit com essa alteração no código
